apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
data:
  spring.datasource.username: eW91cl91c2VybmFtZQ==  # Base64 encoded
  spring.datasource.password: eW91cl9wYXNzd29yZA==  # Base64 encoded